name: Create Q1_archive_README.md

on:
  push:
    branches:
      - main

jobs:
  copy_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy README.md to Q1_archive_README.md
      run: cp README.md Q1_archive_README.md

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Scarlet76"
        git config --global user.email "scarlet0ciel0@gmail.com"
        git add Q1_archive_README.md
        git diff --quiet || git commit -m "Création Q1_archive_README.md"
        git pull --rebase origin main
        git push
