name: Create Q2_archive_README.md

on:
  push:
    branches:
      - main

jobs:
  create_q2_archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Q2_archive_README.md
      run: |
        echo "Nom et Prénom : Scarlet Dupin" > Q2_archive_README.md
        echo "Date et Heure : $(date)" >> Q2_archive_README.md
        echo "" >> Q2_archive_README.md
        echo "Contenu de README.md :" >> Q2_archive_README.md
        echo "--------------------" >> Q2_archive_README.md
        cat README.md >> Q2_archive_README.md

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Scarlet76"
        git config --global user.email "scarlet0ciel0@gmail.com"
        git add Q2_archive_README.md
        git diff --quiet || git commit -m "Création Q2_archive_README.md"
        git pull --rebase origin main || git stash && git pull --rebase origin main && git stash pop
        git push
