name: Create Q4_archive_date.txt

on:
  push:
    branches:
      - main

jobs:
  create_q4_archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create Q4_archive_date.txt
      run: |
        # Récupérer la date au format JJ-MM-AAAA
        DATE=$(date +'%d-%m-%Y')

        # Créer le fichier texte avec les informations
        echo "Nom et Prénom : Lucas Langlois" > "Q4_archive_${DATE}.txt"
        echo "" >> "Q4_archive_${DATE}.txt"
        echo "Contenu de Q4.java :" >> "Q4_archive_${DATE}.txt"
        echo "--------------------" >> "Q4_archive_${DATE}.txt"
        
        # Ajouter le contenu de Q4.java
        cat Q4.java >> "Q4_archive_${DATE}.txt"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Scarlet76"
        git config --global user.email "scarlet0ciel0@gmail.com"
        git add "Q4_archive_${DATE}.txt"
        git commit -m "Création de Q4_archive_${DATE}.txt avec le contenu de Q4.java"
        git pull --rebase origin main || git stash && git pull --rebase origin main && git stash pop
        git push
