name: Create Q4_archive_date.txt

on:
  push:
    branches:
      - main

jobs:
  create_q4_archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate the date and create file
      run: |
        # Récupérer la date au format JJ-MM-AAAA
        DATE=$(date +'%d-%m-%Y')

        # Afficher la date générée pour vérification
        echo "Generated date: $DATE"

        # Créer le fichier texte avec les informations
        echo "Nom et Prénom : Lucas Langlois" > "Q4_archive_${DATE}.txt"
        echo "" >> "Q4_archive_${DATE}.txt"
        echo "Contenu de Q4.java :" >> "Q4_archive_${DATE}.txt"
        echo "--------------------" >> "Q4_archive_${DATE}.txt"
        
        # Ajouter le contenu de Q4.java
        cat Q4.java >> "Q4_archive_${DATE}.txt"

        # Afficher les fichiers créés pour vérification
        echo "Files after creation:"
        ls -l

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Scarlet76"
        git config --global user.email "scarlet0ciel0@gmail.com"
        
        # Ajouter le fichier créé
        git add "Q4_archive_${DATE}.txt"

        # Vérifier s'il y a des changements à committer
        git diff --cached --exit-code || git commit -m "Création de Q4_archive_${DATE}.txt avec le contenu de Q4.java"

        # Pousser les changements si un commit a eu lieu
        git push
