name: Create Q4_archive_date.txt

on:
  push:
    branches:
      - main

jobs:
  create_q4_archive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate the date and create file
      run: |
        # Récupérer la date au format JJ-MM-AAAA
        DATE=$(date +'%d-%m-%Y')

        # Afficher la date générée pour vérification
        echo "Generated date: $DATE"

        # Créer le fichier texte avec les informations
        FILE_NAME="Q4_archive_${DATE}.txt"
        echo "Nom et Prénom : Lucas Langlois" > "$FILE_NAME"
        echo "" >> "$FILE_NAME"
        echo "Contenu de Q4.java :" >> "$FILE_NAME"
        echo "--------------------" >> "$FILE_NAME"
        
        # Ajouter le contenu de Q4.java
        cat Q4.java >> "$FILE_NAME"

        # Afficher les fichiers créés pour vérification
        echo "Files after creation:"
        ls -l

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Scarlet76"
        git config --global user.email "scarlet0ciel0@gmail.com"

        # Vérifier si le fichier existe déjà
        if git ls-files --error-unmatch "$FILE_NAME" > /dev/null 2>&1; then
          echo "$FILE_NAME already exists in the repository."
          
          # Vérifier si le contenu du fichier est le même
          if cmp --silent "$FILE_NAME" "$(git show HEAD:$FILE_NAME)"; then
            echo "$FILE_NAME has not changed. No need to commit."
            exit 0
          fi
        fi

        # Ajouter le fichier créé
        git add "$FILE_NAME"

        # Commit et push
        git commit -m "Création de $FILE_NAME avec le contenu de Q4.java"
        git push
