name: Create Q4_archive.txt

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_and_push_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up date
      id: date
      run: echo "current_date=$(date +'%d-%m-%Y')" >> $GITHUB_ENV

    - name: Create Q4_archive_date.txt
      run: |
        echo "Prénom Nom : Lucas Langlois " > Q4_archive_${{ env.current_date }}.txt
        echo "Fichier Q4.java :" >> Q4_archive_${{ env.current_date }}.txt
        cat Q4.java >> Q4_archive_${{ env.current_date }}.txt

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "Scarlet76"
        git config --global user.email "scarlet0ciel0@gmail.com"
        git add Q4_archive_${{ env.current_date }}.txt
        git commit -m "Création Q4_archive_${{ env.current_date }}.txt"
        git push
